import type { Metadata, Viewport } from "next";
import { Poppins } from "next/font/google";
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";
import { TrustBanner } from "@/components/trust-banner";
import { Analytics } from "@/components/analytics";
import { CookieConsent } from "@/components/cookie-consent";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export const metadata: Metadata = {
  metadataBase: new URL("https://www.powerbug.fr"),
  title: {
    default: "PowerBug France | Chariots Electriques de Golf Premium",
    template: "%s | PowerBug France",
  },
  description:
    "Distributeur exclusif France des chariots electriques de golf PowerBug. NX Lithium et NX DHC Lithium, accessoires, batteries. Livraison France entiere.",
  alternates: {
    canonical: "/",
    languages: {
      "fr-FR": "https://www.powerbug.fr",
      "x-default": "https://www.powerbug.fr",
    },
  },
  openGraph: {
    title: "PowerBug France | Chariots Electriques de Golf Premium",
    description:
      "Distributeur exclusif France des chariots electriques de golf PowerBug. Qualite britannique depuis 2003.",
    type: "website",
    locale: "fr_FR",
    siteName: "PowerBug France",
    url: "https://www.powerbug.fr",
    // Image auto-generated by app/opengraph-image.tsx (1200×630)
  },
  verification: {
    google: "jysyw4S7gFnMSHyidOa5uAsCTRQM8z-BnQ-G4lDFZKc",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-snippet": -1,
      "max-image-preview": "large",
      "max-video-preview": -1,
    },
  },
  twitter: {
    card: "summary_large_image",
    title: "PowerBug France | Chariots Électriques de Golf Premium",
    description: "Distributeur exclusif France des chariots électriques de golf PowerBug. Qualité britannique, livraison France entière.",
  },
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "32x32" },
      { url: "/icon-192.png", sizes: "192x192", type: "image/png" },
    ],
    apple: "/apple-touch-icon.png",
  },
};

const schemaWebsite = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  name: "PowerBug France",
  url: "https://www.powerbug.fr",
  description: "Distributeur exclusif France des chariots électriques de golf PowerBug",
};

const schemaOrganization = {
  "@context": "https://schema.org",
  "@type": ["Organization", "Store"],
  name: "PowerBug France",
  legalName: "PRO GOLF DISTRIBUTION",
  url: "https://www.powerbug.fr",
  description: "Distributeur exclusif France des chariots électriques de golf PowerBug depuis 2024",
  email: "contact@powerbug.fr",
  telephone: "+33788239784",
  address: {
    "@type": "PostalAddress",
    streetAddress: "Domaine de Riquetti",
    addressLocality: "Aix-en-Provence",
    postalCode: "13290",
    addressCountry: "FR",
  },
  areaServed: {
    "@type": "Country",
    name: "France",
  },
  priceRange: "€€",
  currenciesAccepted: "EUR",
  paymentAccepted: "Carte bancaire, Apple Pay, Google Pay",
  contactPoint: {
    "@type": "ContactPoint",
    telephone: "+33788239784",
    contactType: "customer service",
    availableLanguage: "French",
  },
  sameAs: [],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${poppins.variable} antialiased bg-white text-[#0F0F10]`}>
        <Header />
        <TrustBanner />
        <main className="min-h-screen pb-24 md:pb-0">{children}</main>
        <Footer />
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schemaWebsite) }} />
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schemaOrganization) }} />
        <Analytics />
        <CookieConsent />
      </body>
    </html>
  );
}
