-- Migration 013 : Descriptions enrichies SEO pour accessoires et pièces détachées
-- Source : golfdesmarques.com (distributeur officiel France) + powerbug.co.uk
-- Objectif : 150-200 mots par produit pour le référencement naturel

-- ============================================================
-- ACCESSOIRES
-- ============================================================

UPDATE products SET description = 'Le porte-parapluie PowerBug est spécifiquement conçu pour les chariots électriques de la gamme NX. Il se fixe directement sur la station d''accessoires intégrée de la poignée du chariot, sans aucun matériel de montage supplémentaire ni modification du chariot. Son système de pivot unique garantit une fixation stable et sécurisée, même par grand vent. Compatible avec les manches de parapluie de golf jusqu''à 37 mm de diamètre, il s''adapte à la quasi-totalité des parapluies du marché. L''un de ses principaux atouts est de rester fixé lorsque le chariot est replié, ce qui simplifie considérablement le chargement et le déchargement du véhicule après la partie. Fabriqué en polymères résistants aux UV et aux variations de température, il conserve ses propriétés mécaniques en toutes saisons. Sa finition noire mate s''intègre parfaitement à l''esthétique contemporaine des chariots NX. Au-delà de la protection contre la pluie, le porte-parapluie peut également maintenir un parasol anti-UV, créant une zone d''ombre au-dessus du chariot pour protéger vos affaires et boissons lors des journées ensoleillées. Un accessoire simple, robuste et indispensable pour jouer confortablement par tous les temps.'
WHERE slug = 'porte-parapluie' AND store = 'powerbug';

UPDATE products SET description = 'La housse de transport PowerBug NX est un accessoire indispensable pour tout golfeur souhaitant combiner propreté et praticité lors de ses déplacements. Conçue pour protéger votre chariot électrique des petits chocs et des rayures, elle isole efficacement la saleté, l''herbe et l''humidité accumulées sur le parcours, préservant ainsi l''habitacle de votre véhicule. Fabriquée dans des matériaux techniques haute qualité offrant une excellente résistance à l''abrasion et aux déchirures, cette housse est pensée pour durer. Sa compatibilité universelle en fait un atout : optimisée pour les modèles PowerBug NX et NX DHC, elle s''adapte également à la plupart des chariots électriques Motocaddy et PowaKaddy du marché. Ses dimensions généreuses accueillent les chariots repliés jusqu''à 92 cm de longueur, 62 cm de largeur et 52 cm de hauteur. Des poignées solides facilitent la manipulation et le transport, tandis que la housse se replie sur elle-même pour un stockage minimal lorsqu''elle n''est pas utilisée. Un investissement rentable pour maintenir votre chariot propre, protéger votre voiture et prolonger la durée de vie de votre équipement de golf.'
WHERE slug = 'housse-transport' AND store = 'powerbug';

UPDATE products SET description = 'L''extension de porte-parapluie PowerBug NX répond à un besoin précis : offrir une hauteur supplémentaire aux golfeurs qui souhaitent plus d''aisance et de mobilité lors des parties pluvieuses. Elle ajoute 15 cm de hauteur par rapport aux supports standards, ce qui améliore significativement l''ergonomie en élevant le point d''ancrage du parapluie. Résultat : une meilleure visibilité, une plus grande liberté de mouvement entre les trous, et la possibilité d''accéder facilement à ses clubs sans se baisser. L''installation est ultra simple : aucun outil n''est nécessaire, l''extension s''insère en quelques secondes et se retire tout aussi facilement pour le rangement dans la poche du sac de golf. Sa construction robuste est conçue pour résister au vent et au poids des parapluies de golf, en répartissant les forces de manière optimale sur la structure du support. Compatible avec les chariots PowerBug NX, Motocaddy, Powakaddy et la grande majorité des chariots électriques standard du marché. Fonctionne avec tout parapluie de golf doté d''une poignée droite. Un petit accessoire qui fait une grande différence pour les golfeurs de grande taille ou ceux qui veulent simplement plus de confort.'
WHERE slug = 'umbrella-holder-extension' AND store = 'powerbug';

UPDATE products SET description = 'Le porte-carte de score PowerBug NX est un accessoire essentiel pour les golfeurs soucieux de leur organisation sur le parcours. Son couvercle transparent rigide protège efficacement votre carte de score de la pluie et du vent, tout en maintenant une visibilité parfaite pour noter vos scores au fil des trous. Sa conception ne se limite pas à protéger le papier : il intègre un espace dédié pouvant accueillir jusqu''à cinq tees ainsi qu''un porte-crayon, gardant tout le matériel de score à portée de main sans avoir à fouiller dans le sac. Fabriqué en matériaux résistants aux UV avec des charnières renforcées, il est conçu pour supporter une utilisation quotidienne intensive et les ouvertures et fermetures répétées sur plusieurs saisons. Son système de fixation s''intègre spécifiquement aux chariots de la gamme NX, éliminant les vibrations pendant le transport et garantissant une stabilité parfaite sur tout type de terrain. Compact et léger, il n''encombre pas le chariot et passe inaperçu lorsqu''il n''est pas utilisé. Un accessoire pratique qui améliore concrètement la gestion de votre partie et garde vos statistiques protégées et bien organisées tout au long du parcours.'
WHERE slug = 'scorecard-holder' AND store = 'powerbug';

UPDATE products SET description = 'Le sac isotherme PowerBug NX est l''accessoire idéal pour les golfeurs qui tiennent à rester hydratés et à garder leurs encas au frais tout au long du parcours. Son compartiment principal zippé bénéficie d''une isolation thermique performante qui maintient la fraîcheur des boissons et des aliments, avec un espace suffisant pour accueillir des packs de glace. Une poche frontale sécurisée permet de ranger vos objets de valeur — téléphone, clés, portefeuille — en toute sécurité et à portée de main. La poignée ergonomique intégrée permet d''utiliser le sac de façon autonome, indépendamment du chariot. Des sangles élastiques arrière assurent une fixation stable et sans glissement sur le cadre du chariot, quelle que soit la vitesse ou la nature du terrain. Compatible avec les chariots PowerBug NX et NX DHC, il s''adapte également à la plupart des marques de chariots électriques du marché, dont Motocaddy. Poids : 1 kg. Un compagnon de parcours pratique qui allie confort, organisation et fraîcheur pour profiter pleinement de chaque partie, été comme hiver.'
WHERE slug = 'sac-isotherme' AND store = 'powerbug';

UPDATE products SET description = 'Le porte-gobelet PowerBug NX est l''accessoire indispensable pour maintenir une hydratation optimale tout au long de votre parcours de golf. Son design spacieux et repensé accueille une grande variété de contenants : canettes standard, grandes bouteilles d''eau, bouteilles sport et thermos jusqu''à un diamètre généreux. L''installation est remarquablement simple sur les modèles NX : il suffit de clipser le porte-gobelet sur la station d''accessoires intégrée de la poignée du chariot, sans outil ni modification. Son positionnement ergonomique garantit un accès facile à votre boisson sans gêner la commande du chariot ni perturber votre gestuelle de jeu. Fabriqué en plastique haute résistance, il supporte l''exposition aux UV et les variations de température de saison en saison sans se déformer ni se fragiliser. Sa fixation sécurisée empêche tout renversement, même sur terrain accidenté. Une large compatibilité en fait un accessoire polyvalent : il fonctionne sur tous les modèles PowerBug et s''adapte également aux chariots Motocaddy fabriqués après 2018. Léger, discret et parfaitement intégré à l''esthétique du chariot NX, c''est un petit détail qui change vraiment la qualité d''une partie.'
WHERE slug = 'drinks-holder' AND store = 'powerbug';

UPDATE products SET description = 'Le support téléphone PowerBug NX est l''accessoire indispensable du golfeur connecté d''aujourd''hui. Spécifiquement conçu pour la gamme NX, il transforme la console de commande du chariot en véritable hub d''information, permettant un accès immédiat aux données de parcours sans jamais fouiller dans les poches ou le sac. Compatible avec une large gamme d''appareils mobiles — des smartphones compacts aux modèles XXL, en passant par les GPS golf dédiés — il maintient le dispositif fermement en place grâce à sa conception renforcée qui absorbe les vibrations et les chocs des terrains irréguliers. Fabriqué en matériaux résistants aux UV et aux températures extrêmes, il conserve son efficacité en toutes saisons. Son montage ergonomique ne nécessite aucun outil et positionne l''écran dans le champ de vision naturel du golfeur, sans contraindre la prise en main de la commande du chariot. Avoir son téléphone ou GPS à portée de regard permet de consulter instantanément les distances aux obstacles, les plans de trou et les données de performance, sans rompre la concentration ni ralentir le rythme de jeu. Un accessoire qui intègre parfaitement les outils numériques dans l''expérience du golf moderne. Poids : 50 g.'
WHERE slug = 'support-telephone' AND store = 'powerbug';

UPDATE products SET description = 'Les moufles chauffantes PowerBug NX sont l''accessoire ultime pour les golfeurs qui refusent de laisser le froid interrompre leur passion. Conçues spécifiquement pour les chariots de la gamme NX, elles permettent de maintenir le confort des mains entre les coups, quelle que soit la température extérieure. Leur système de chauffage propose trois réglages ajustables, permettant de personnaliser la température selon les conditions météo et les préférences de chaque joueur, du simple confort hivernal aux journées de gel intense. Leur grande innovation réside dans leur alimentation : les moufles se branchent directement sur le port USB intégré à la poignée du chariot NX, éliminant totalement le besoin de piles ou de batteries externes et préservant intégralement l''autonomie du chariot sur l''ensemble du parcours. Fabriquées avec des matériaux isolants de qualité et des textiles résistants au vent et à l''humidité, elles permettent une insertion et un retrait rapides des mains sans perturber le rythme de jeu. Leur design ergonomique, spécifiquement conçu pour les poignées NX, assure un maintien sécurisé tout en conservant un accès total aux boutons de réglage de vitesse. En prévenant l''engourdissement des doigts causé par le froid, elles aident à conserver la sensibilité de grip et la précision de swing essentielles à un jeu régulier. Référence : 24620.'
WHERE slug = 'mitaines-electriques' AND store = 'powerbug';

UPDATE products SET description = 'Le sac de rangement PowerBug NX est la solution idéale pour les golfeurs soucieux de la propreté de leur véhicule et de l''organisation de leur équipement. Cet accessoire robuste isole le chariot replié du reste du coffre, empêchant les traces d''herbe, les taches de boue et l''humidité accumulées sur le parcours de souiller les revêtements intérieurs du véhicule — un avantage non négligeable pour préserver la valeur à la revente de votre voiture. Son ouverture par le dessus facilite le chargement et le déchargement du chariot replié, même seul. Sa construction semi-rigide, avec panneau arrière rigide et parois semi-rigides, assure une excellente stabilité du contenu et protège le chariot des petits chocs pendant le transport. Un système de ventilation naturelle permet la circulation d''air à l''intérieur du sac, favorisant le séchage des équipements mouillés et évitant les mauvaises odeurs dues à l''humidité stagnante. Ses dimensions généreuses (L 90 cm × l 46 cm × H 61 cm) accueillent les chariots PowerBug NX et NX DHC repliés, ainsi que de nombreuses autres marques de chariots électriques incluant Motocaddy et Powakaddy. Il se replie complètement à plat lorsqu''il n''est pas utilisé pour un rangement minimal dans le coffre ou le garage. Fabriqué en textile technique durable, facile d''entretien. Poids : 50 g.'
WHERE slug = 'sac-rangement' AND store = 'powerbug';

-- ============================================================
-- PIÈCES DÉTACHÉES
-- ============================================================

UPDATE products SET description = 'Le chargeur de batterie Lithium PowerBug NX est l''équipement officiel conçu pour recharger votre batterie Lithium NX en toute sécurité et efficacité. En tant que chargeur d''origine, il délivre des cycles de charge optimisés spécifiquement pour la chimie des cellules de la batterie NX, prolongeant ainsi sa durée de vie et maintenant des performances constantes sur 18 trous ou plus. Son temps de charge de 3 à 6 heures depuis un état complètement déchargé vous garantit une batterie prête pour la prochaine partie. Les indicateurs visuels de charge intégrés permettent de suivre l''état de la recharge en un coup d''œil. Plusieurs systèmes de sécurité sont intégrés : protection contre la surcharge, les courts-circuits, les inversions de polarité et les surtensions, protégeant à la fois la batterie et le réseau électrique de votre domicile. Son design compact et léger facilite le transport pour les golfeurs qui voyagent en déplacement ou en tournoi. Utiliser un chargeur non officiel avec votre batterie NX représente un risque réel : endommagement irréversible des cellules, réduction de l''autonomie et invalidation de la garantie. Le chargeur PowerBug d''origine est la seule solution garantissant la compatibilité totale et la préservation de votre investissement sur le long terme. Branchement simple sur prise secteur standard.'
WHERE slug = 'chargeur-batterie' AND store = 'powerbug';

UPDATE products SET description = 'L''ensemble roue avant PowerBug NX est la pièce de rechange officielle pour maintenir votre chariot électrique en parfait état de fonctionnement, saison après saison. Ce kit complet de remplacement comprend tous les éléments nécessaires à une remise en état optimale : un boîtier de protection haute résistance conçu pour protéger les composants internes des débris, cailloux et projections de boue ; une roue avec une bande de roulement spécifiquement adaptée aux surfaces des parcours de golf ; et un axe réglable permettant un alignement précis pour une direction fluide et précise. Remplacer l''ensemble roue avant dans son intégralité, plutôt que pièce par pièce, garantit une restauration optimale de la trajectoire du chariot et réduit la consommation d''énergie de la batterie en éliminant toute friction parasite. Les matériaux sélectionnés résistent aux conditions météo les plus diverses — pluie, boue, gel, chaleur — assurant une durabilité optimale sur le long terme. L''utilisation de composants OEM d''origine PowerBug préserve l''intégrité structurelle du châssis et prévient l''usure prématurée des pièces mécaniques adjacentes. Compatible avec les chariots PowerBug NX Lithium et NX DHC Lithium. Une pièce essentielle pour prolonger la durée de vie de votre chariot et maintenir ses performances d''origine.'
WHERE slug = 'roue-avant-complete' AND store = 'powerbug';

UPDATE products SET description = 'Le moteur de remplacement 200W PowerBug NX est la pièce officielle pour redonner à votre chariot électrique toutes ses performances d''origine. Développant une puissance de 200 watts, ce moteur est spécifiquement calibré pour les chariots de la gamme NX, offrant le parfait équilibre entre force de traction et efficience énergétique pour une autonomie maximale sur l''ensemble du parcours. Son fonctionnement silencieux minimise les perturbations sur le green et entre les trous, respectant ainsi l''étiquette du golf. Son couple amélioré lui permet de franchir sans effort les montées, les terrains détrempés et les passages difficiles que l''on rencontre sur les parcours vallonnés. Côté technique, il s''agit d''un moteur à courant continu avec un boîtier robuste doté d''un système de dissipation thermique efficace. Son étanchéité renforcée le protège de l''eau, de la poussière et des débris, pour un fonctionnement fiable par tous les temps. Ses connecteurs standards facilitent l''installation et garantissent une interface parfaite avec le système électronique du chariot NX. Remplacer le moteur seul est une solution économique qui prolonge significativement la durée de vie du chariot sans avoir à investir dans un nouvel équipement complet. L''utilisation d''un composant OEM d''origine préserve les garanties et l''intégrité du système électronique.'
WHERE slug = 'moteur-200w-nx' AND store = 'powerbug';

UPDATE products SET description = 'Le moteur de remplacement PowerBug NX DHC est la pièce officielle spécifiquement conçue pour les chariots équipés du système Downhill Control (DHC). Ce moteur joue un rôle double et essentiel : il assure la propulsion sur terrain plat et lors des montées, tout en prenant en charge la régulation automatique de la vitesse lors des descentes, garantissant ainsi un contrôle sécurisé du chariot sur les parcours vallonnés. Cette fonction de régulation DHC est intégrée directement dans les composants électroniques du moteur, ce qui implique impérativement l''utilisation d''une pièce compatible — un moteur standard 200W NX ne peut pas remplacer ce modèle sans désactiver la fonction de contrôle en descente. Compatible avec les chariots portant les préfixes de numéro de série TPB P10 et TPB P9. Comme pour l''ensemble de la gamme PowerBug, ce moteur bénéficie d''une conception étanche protégeant les bobines internes de l''humidité et des débris, d''un fonctionnement silencieux adapté aux exigences du golf, et de connecteurs standards pour une installation simplifiée. L''utilisation d''une pièce OEM d''origine garantit la pleine compatibilité avec le système de contrôle électronique du chariot et préserve la sécurité du golfeur, notamment lors des descentes. Référence : 24630. Poids : 50 g.'
WHERE slug = 'moteur-nx-dhc' AND store = 'powerbug';
